apiVersion: v1
kind: Namespace
metadata:
  name: cloudmare

---

apiVersion: v1
kind: Secret
metadata:
  name: db-connection
  namespace: cloudmare
type: Opaque
stringData:
  DefaultConnection: "Server=mssql;Database=Gateway;User=sa;Password=<password>"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pvc
  namespace: cloudmare
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  namespace: cloudmare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "<password>"
          volumeMounts:
            - name: mssql-storage
              mountPath: /var/opt/mssql
      volumes:
        - name: mssql-storage
          persistentVolumeClaim:
            claimName: mssql-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: mssql
  namespace: cloudmare
spec:
  ports:
    - port: 1433
      targetPort: 1433
  selector:
    app: mssql

---

# Microservice: bookms
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookms
  namespace: cloudmare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookms
  template:
    metadata:
      labels:
        app: bookms
    spec:
      containers:
        - name: bookms
          image: roccobalocco/book:latest
          ports:
            - containerPort: 80
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: db-connection
                  key: DefaultConnection

---

apiVersion: v1
kind: Service
metadata:
  name: bookms
  namespace: cloudmare
spec:
  ports:
    - port: 80
  selector:
    app: bookms

---

# Microservice: userms
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userms
  namespace: cloudmare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userms
  template:
    metadata:
      labels:
        app: userms
    spec:
      containers:
        - name: userms
          image: roccobalocco/user:latest
          ports:
            - containerPort: 80
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: db-connection
                  key: DefaultConnection

---

apiVersion: v1
kind: Service
metadata:
  name: userms
  namespace: cloudmare
spec:
  ports:
    - port: 81
  selector:
    app: userms

---

# Microservice: loanms
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loanms
  namespace: cloudmare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loanms
  template:
    metadata:
      labels:
        app: loanms
    spec:
      containers:
        - name: loanms
          image: roccobalocco/loan:latest
          ports:
            - containerPort: 80
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: db-connection
                  key: DefaultConnection

---

apiVersion: v1
kind: Service
metadata:
  name: loanms
  namespace: cloudmare
spec:
  ports:
    - port: 82
  selector:
    app: loanms

---

# Microservice: roomms
apiVersion: apps/v1
kind: Deployment
metadata:
  name: roomms
  namespace: cloudmare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roomms
  template:
    metadata:
      labels:
        app: roomms
    spec:
      containers:
        - name: roomms
          image: roccobalocco/room:latest
          ports:
            - containerPort: 80
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: db-connection
                  key: DefaultConnection

---

apiVersion: v1
kind: Service
metadata:
  name: roomms
  namespace: cloudmare
spec:
  ports:
    - port: 83
  selector:
    app: roomms

---

# API Gateway
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
  namespace: cloudmare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: apigateway
          image: roccobalocco/api-gateway:latest
          ports:
            - containerPort: 80
          env:
            - name: ConnectionStrings__Local
              valueFrom:
                secretKeyRef:
                  name: db-connection
                  key: DefaultConnection
            - name: MicroServicesOptions__Book
              value: "http://bookms:80"
            - name: MicroServicesOptions__User
              value: "http://userms:81"
            - name: MicroServicesOptions__Loan
              value: "http://loanms:82"
            - name: MicroServicesOptions__Room
              value: "http://roomms:83"

---

apiVersion: v1
kind: Service
metadata:
  name: apigateway
  namespace: cloudmare
spec:
  ports:
    - port: 84
  selector:
    app: apigateway
