apiVersion: v1
kind: Namespace
metadata:
  name: cloudmare

---

apiVersion: v1
kind: Secret
metadata:
  name: db-connection
  namespace: cloudmare
type: Opaque
stringData:
  DefaultConnection: "Server=mssql;Database=Gateway;User=sa;Password=<password>"
  Local: "Server=mssql;Database=Gateway;User=sa;Password=<password>"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pvc
  namespace: cloudmare
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  namespace: cloudmare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "<password>"
          volumeMounts:
            - name: mssql-storage
              mountPath: /var/opt/mssql
      volumes:
        - name: mssql-storage
          persistentVolumeClaim:
            claimName: mssql-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: mssql
  namespace: cloudmare
spec:
  ports:
    - port: 1433
      targetPort: 1433
  selector:
    app: mssql

---

# bookms Deployment & Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookms
  namespace: cloudmare
spec:
  selector:
    matchLabels:
      app: bookms
  template:
    metadata:
      labels:
        app: bookms
    spec:
      containers:
        - name: bookms
          image: roccobalocco/book:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 500m
          env:
            - name: ConnectionStrings__Local
              valueFrom:
                secretKeyRef:
                  name: db-connection
                  key: DefaultConnection

---

apiVersion: v1
kind: Service
metadata:
  name: bookms
  namespace: cloudmare
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: bookms

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bookms-hpa
  namespace: cloudmare
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bookms
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20

---

# userms Deployment & Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userms
  namespace: cloudmare
spec:
  selector:
    matchLabels:
      app: userms
  template:
    metadata:
      labels:
        app: userms
    spec:
      containers:
        - name: userms
          image: roccobalocco/user:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 500m
          env:
            - name: ConnectionStrings__Local
              valueFrom:
                secretKeyRef:
                  name: db-connection
                  key: DefaultConnection

---

apiVersion: v1
kind: Service
metadata:
  name: userms
  namespace: cloudmare
spec:
  ports:
    - port: 81
      targetPort: 8080
  selector:
    app: userms

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: userms-hpa
  namespace: cloudmare
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: userms
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20

---

# loanms Deployment & Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loanms
  namespace: cloudmare
spec:
  selector:
    matchLabels:
      app: loanms
  template:
    metadata:
      labels:
        app: loanms
    spec:
      containers:
        - name: loanms
          image: roccobalocco/loan:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 500m
          env:
            - name: ConnectionStrings__Local
              valueFrom:
                secretKeyRef:
                  name: db-connection
                  key: DefaultConnection

---

apiVersion: v1
kind: Service
metadata:
  name: loanms
  namespace: cloudmare
spec:
  ports:
    - port: 82
      targetPort: 8080
  selector:
    app: loanms

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: loanms-hpa
  namespace: cloudmare
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: loanms
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20

---

# roomms Deployment & Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: roomms
  namespace: cloudmare
spec:
  selector:
    matchLabels:
      app: roomms
  template:
    metadata:
      labels:
        app: roomms
    spec:
      containers:
        - name: roomms
          image: roccobalocco/room:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 500m
          env:
            - name: ConnectionStrings__Local
              valueFrom:
                secretKeyRef:
                  name: db-connection
                  key: DefaultConnection

---

apiVersion: v1
kind: Service
metadata:
  name: roomms
  namespace: cloudmare
spec:
  ports:
    - port: 83
      targetPort: 8080
  selector:
    app: roomms

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: roomms-hpa
  namespace: cloudmare
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: roomms
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20

---

# API Gateway Deployment & Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
  namespace: cloudmare
spec:
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: apigateway
          image: roccobalocco/api-gateway:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 500m
          env:
            - name: ConnectionStrings__Local
              valueFrom:
                secretKeyRef:
                  name: db-connection
                  key: DefaultConnection
            - name: MicroServicesOptions__Book
              value: "http://bookms:80"
            - name: MicroServicesOptions__User
              value: "http://userms:81"
            - name: MicroServicesOptions__Loan
              value: "http://loanms:82"
            - name: MicroServicesOptions__Room
              value: "http://roomms:83"

---

apiVersion: v1
kind: Service
metadata:
  name: apigateway
  namespace: cloudmare
spec:
  ports:
    - port: 84
      targetPort: 8080
  selector:
    app: apigateway

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: apigateway-hpa
  namespace: cloudmare
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apigateway
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
